# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

"""
This module provides a simple interface to the OIFITSlib merge
functionality. Two functions are provided, both of which take two or
more oifits.OiFits instances, and return a new OiFits instance
containing the merged dataset.

merge() merges the OiFits instances supplied as its arguments; mergelist()
merges instances supplied in a list.

>>> import oifits, oimerge
>>> o1 = oifits.OiFits('testdata.fits')
>>> o2 = oifits.OiFits('bigtest2.fits')
>>> merged = oimerge.merge(o1, o2)
>>> print len(merged.vis2List)
3
>>> print len(merged.t3List)
3

"""

import _oimerge
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


def _test():
  import doctest
  doctest.testmod()

if __name__ == '__main__':
  _test()

def merge(*args):
  """merge(OiFits a, OiFits b, ...) -> OiFits merged"""
  return mergelist(list(args))


def mergelist(*args):
  """mergelist([OiFits a, OiFits b, ...]) -> OiFits merged"""
  return _oimerge.mergelist(*args)


